
# ------ root_path ------
root_path: "/data/xinhua/Datasets"
ood_dataset_path: "/data/xinhua/Datasets/ood-benchmark/imagenet"

# ------ id dataset------

# id_dataset: 'imagenet100'
# id_dataset: 'dtd' 
# id_dataset: 'food101'  
# id_dataset: 'stanford_cars' 
# id_dataset: 'caltech101' 
# id_dataset: 'oxford_flowers'
# id_dataset: 'oxford_pets'

id_dataset: 'imagenet'  
# id_dataset: 'eurosat'
# id_dataset: 'fgvc'
# id_dataset: 'ucf101'

#------ ood_dataset ------
# ood_dataset: 'SUN'
# ood_dataset: 'iNaturalist'
# ood_dataset: 'Places'
# ood_dataset: 'dtd'
# ood_dataset: 'OpenImage_O'
# ood_dataset: 'NINCO'
# ood_dataset: 'Imagenet-o'
# ood_dataset: 'ssb_hard'

ood_dataset: 'common'
# ood_dataset: 'challenging'
# ood_dataset: 'nearood'
# ood_dataset: 'all'



# ------ Hyperparamters ------
seed: 5

shots: 16
backbone: 'ViT-B/16'
K: 3
csc: False
template: 'a photo of a'

lr: 0.002 # 0.0002  0.02 0.002
fine_tune_train_epoch: 50  # 200 30
fine_tune_batch_size: 160  # 160 100

test_batch_size: 250
